---
- name: Listen for events on dt_webhook
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_webhook: #use dt_webhook as source for ansible-rulebook 
        host: 0.0.0.0
        port: 6008
        token: '{{ var_eda_token }}' 

  rules:
    - name: Failure Rate Increase
      condition: event.payload.eventData["event.name"] is match ("Failure rate increase")
      action:
        run_job_template:
          name: "Reset canary weighting"
          organization: "Default"    
  - name: Preemptive scaling 
        condition: event.payload.eventData["event.category"] is match ("CUSTOM_ALERT") and event.payload.eventData["event.description"] is match ("The CPU usage % value was above normal behavior.")
        action:
          run_job_template:
            name: "ScalingCPU"
            organization: "Default"    
          #run_playbook: #use run_playbook for local tests with ansible-rulebook 
            #name: playbooks/run-task.yml   
  - name: Preemptive Disk management 
        condition: event.payload.eventData["event.category"] is match ("CUSTOM_ALERT") and event.payload.eventData["event.description"] is match ("The Disk used % value was above normal behavior.")
        action:
          run_job_template:
            name: "ScalingDisk"
            organization: "Default"    
          #run_playbook: #use run_playbook for local tests with ansible-rulebook 
            #name: playbooks/run-task.yml   
